# Generated by Django 3.1.4 on 2020-12-07 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('booked_route', models.CharField(max_length=30, null=True)),
                ('route_id', models.IntegerField(null=True)),
                ('booked_seats', models.IntegerField(null=True)),
                ('booked_date', models.DateField(null=True)),
                ('pname', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=2, null=True)),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=255)),
                ('wheelchair_needed', models.CharField(default='0', max_length=1, null=True)),
                ('adults', models.IntegerField(null=True)),
                ('children', models.IntegerField(null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=6)),
                ('island', models.CharField(max_length=6, null=True)),
                ('fare', models.CharField(max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sailing_route', models.CharField(max_length=30, null=True)),
                ('occupancy', models.IntegerField(null=True)),
                ('wheelchair', models.CharField(default='0', max_length=1, null=True)),
                ('sailing_date', models.DateField(null=True)),
                ('sailing_day', models.CharField(max_length=30, null=True)),
                ('max_fweight', models.DecimalField(decimal_places=0, max_digits=8)),
                ('rem_fweight', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SailingTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_route', models.CharField(max_length=20)),
                ('arrival', models.DecimalField(decimal_places=2, max_digits=4)),
                ('departure', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time_ashore', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('discount', models.BooleanField(default=False)),
                ('ceilidh', models.BooleanField(default=False)),
                ('ceilidh_confirm', models.BooleanField(default=False)),
                ('ceilidh_partner', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
