# Generated by Django 3.1.3 on 2020-11-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('island_name', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('seats', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Islands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_name', models.CharField(max_length=30)),
                ('am_arrival', models.DecimalField(decimal_places=0, max_digits=4)),
                ('am_depart', models.DecimalField(decimal_places=0, max_digits=4)),
                ('pm_arrival', models.DecimalField(decimal_places=0, max_digits=4)),
                ('pm_depart', models.DecimalField(decimal_places=0, max_digits=4)),
                ('seats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('rem', models.DecimalField(decimal_places=0, max_digits=2)),
                ('max_fweight', models.DecimalField(decimal_places=0, max_digits=8)),
                ('rem_fweight', models.DecimalField(decimal_places=0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('date', models.DateField()),
            ],
        ),
    ]
