# Generated by Django 3.1.4 on 2020-12-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailingtimes',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='sailingtimes',
            name='departure',
        ),
        migrations.AddField(
            model_name='sailingtimes',
            name='final_departure',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sailingtimes',
            name='initial_arrival',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sailingtimes',
            name='island_departure',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sailingtimes',
            name='second_arrival',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
