# Generated by Django 3.1.3 on 2020-11-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20201130_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='days',
        ),
        migrations.AddField(
            model_name='booked',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
